### ISSUE TITLE
Cannot Payment with Univa PayPay

### ISSUE THREAD

**Issue by huylong** [univapay/univapay-java-sdk#399]
https://docs.gopay.jp/en/online-payments/#1._create_a_transaction_token
https://docs.gopay.jp/en/References/issuer-token/

From 11/29/2023
I can't make PayPay payments.
Is the paypay connection from you to SBPS stable?
If there are any changes to the API, please let me know.

**Comment by huylong** [comment]
![image](https://github.com/univapay/univapay-java-sdk/assets/19746895/d3c73f0f-5ccd-4987-b598-0c52f717fe1d)

**Comment by kgston** [comment]
Hi, in order to help you with your issue, we will need more information about exactly where the problem is occurring. A video of the process and a description of the steps you are taking to open the link to SBPS would be good for starters.

Just off the top of my head, I want to confirm that you are opening the issuer token link using http POST? The the link is unable to work with a http GET request method.

**Comment by huylong** [comment]
Do you have a link to instructions on how to convert?

**Comment by kgston** [comment]
If you were using GET from before, we have sent out a notification on 2023/07/21 that due to a change in SBPS specifications, they only accept http POST method.

>Do you have a link to instructions on how to convert?

It depends on your implementation, but you will have to create a html form with the `action` parameter as the issuer token url and `method` parameter as `post` and then automatically submit that form using JS.

An example:
https://stackoverflow.com/questions/8389646/send-post-data-on-redirect-with-javascript-jquery

**Comment by huylong** [comment]
I understand.
Thank you so much.
